In [ ]:
import yfinance as yf
import datetime

In [6]:
today = datetime.date.today().strftime('%Y-%m-%d')

In [7]:
vix = yf.Ticker("^VIX").history(start="1900-01-01", end=today)

In [8]:
vix

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
1990-01-02 00:00:00-06:00,17.240000,17.240000,17.240000,17.240000,0,0.0,0.0
1990-01-03 00:00:00-06:00,18.190001,18.190001,18.190001,18.190001,0,0.0,0.0
1990-01-04 00:00:00-06:00,19.219999,19.219999,19.219999,19.219999,0,0.0,0.0
1990-01-05 00:00:00-06:00,20.110001,20.110001,20.110001,20.110001,0,0.0,0.0
1990-01-08 00:00:00-06:00,20.260000,20.260000,20.260000,20.260000,0,0.0,0.0
...,...,...,...,...,...,...,...
2025-06-26 00:00:00-05:00,16.670000,16.780001,16.110001,16.590000,0,0.0,0.0
2025-06-27 00:00:00-05:00,16.309999,17.290001,16.120001,16.320000,0,0.0,0.0
2025-06-30 00:00:00-05:00,17.190001,17.430000,16.549999,16.730000,0,0.0,0.0
2025-07-01 00:00:00-05:00,16.980000,17.480000,16.510000,16.830000,0,0.0,0.0
2025-07-02 00:00:00-05:00,16.750000,17.370001,16.540001,16.639999,0,0.0,0.0